enum SvgAsset {
  logoLandscape('logolandscape'),
  logoIcon('logo_icon'),
  logoIconInverted('logo_icon_inverted'),
  ready('ready_icon'),
  error('error_icon'),
  userCircle('user-circle'),
  user('user'),
  userLocationPin('user_location_pin'),
  userOutlined('user-outlined'),
  paymentMethod('payment_method'),
  point('point'),
  pickUp('pick_up'),
  location('location'),
  locationCover('location_cover'),
  mapPin('map_pin'),
  loader('loader'),
  driver('driver'),
  driverPhotoAlt('driver_photo_alt'),
  car('car'),
  carPhotoAlt('car_photo_alt'),
  carCurrentLocation('car_current_location'),
  cancelRide('cancel_ride'),
  cancel('cancel'),
  clearField('clear_field'),
  seat('seat'),
  walk('walk'),
  finish('finish'),
  welcomeCover('welcome_cover'),
  rideCompletedCover('ride_completed_cover'),
  attention('attention'),
  flagCz('flag_cz'),
  arrowRight('arrow_right'),
  logout('logout'),
  help('help'),
  termsAndService('terms_and_service'),
  arrowRightSpecial('arrow_right_special'),
  backSimple('back_simple'),
  cancelSimple('cancel_simple'),
  okSign('ok_sign'),
  card('card'),
  cardMastercard('card_mastercard'),
  cardVisa('card_visa');

  static const _svgPath = 'assets/svg';
  final String path;

  const SvgAsset(String fileName) : path = '$_svgPath/$fileName.svg';
}
